In [2]:
import numpy as np

In [3]:
# função append
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
np.append(a,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [12]:
array2 = np.append(a,[[5,6]])
print(array2)

[1 2 3 4 5 6]


In [14]:
array3 = np.append(a,[[5,6]], axis=0)
print(array3)

[[1 2]
 [3 4]
 [5 6]]
