In [1]:
# é simple e muito util, saber criar matrizes com NumPy

import numpy as np

# varias listas aleátorias = obs: tamanho igual, ja ja vou testar com tamanhos diferentes
joao_pts = [20,30,40,15]
pedro_pts = [100,24,48,23]
maria_pts = [92,22,34,12]
marcos_pts = [12,34,12,43]

pontos = np.array([joao_pts,pedro_pts,maria_pts,marcos_pts]) 

In [2]:
pontos


array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [3]:
# testando com listas de tamanhos diferentes
joao_pts2 = [20,30,40,15]
pedro_pts2 = [100,24,23]
maria_pts2 = [92,34,12]
marcos_pts2 = [12,34,12,43]

pontos2 = np.array([joao_pts2,pedro_pts2,maria_pts2,marcos_pts2]) 

In [4]:
pontos2

array([list([20, 30, 40, 15]), list([100, 24, 23]), list([92, 34, 12]),
       list([12, 34, 12, 43])], dtype=object)

In [5]:
# buscando uma linha especifica
pontos[0]

array([20, 30, 40, 15])

In [6]:
# buscando um elemento especifico
pontos[1,1]

24

In [8]:
# criando um array para mais tarde transforma-lo em uma matriz 5x4
my_data = np.arange(0,20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
# atenção com essa função pois acho que posso usa-la nos arquivos da IC
mat1 = np.reshape(my_data,(5,4))
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
# buscando um elemento pelo modo que ja conheço, linha/coluna
print(mat1[4,2])

18


In [18]:
# buscando um elemento pela função item, ela conta de forma linear os elementos e me traz o seu valor
lista = [2,5,6,3,4,7,88,99,6,65,12,54,47,00]
mat2 = np.reshape(lista,(2,7))
print(mat2.item(5))

7
