In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [4]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [7]:
# o erro ocorreu pois as dimenssões são diferentes 2x2 / 1x2 , mas existe uma solução, 
# é só fazer uma transposta, assim a segunda fica 2x1 então fica 2x2 /2x1 o numero de colunas da 1¯fica igual 
# ao numero colunas da segunda
b.T

array([[5],
       [6]])

In [9]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])