In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [15]:
# me parece que o array original sempre fica com os mesmos elementos e tamanho
# primeiro passo o array que tera a adição de um item, depois o indice no qual esse indice deve ficar, e em terceiro
# o novo elemento
np.insert(arr,1,10)

array([ 1, 10,  2,  3])

In [17]:
# coloque o elemento 999 no indice 0 do array arr
np.insert(arr,0,999)

array([999,   1,   2,   3])

In [19]:
np.insert(arr,2,33)

array([ 1,  2, 33,  3])

In [21]:
# comprova minha teoria, pois modifiquei o arr acima e aqui ele esta original ainda 
arr

array([1, 2, 3])

In [24]:
a = np.array([[1,2],[3,4]])
# mostra o array
print("matriz = \n",a)
# mostra a quantidade de dimenssões
print("quantidade de dimenssões",a.ndim)

matriz = 
 [[1 2]
 [3 4]]
quantidade de dimenssões 2


In [26]:
# somar os elementos do eixo zero e do eixo um
# eixo zero é a linha vertical (coluna)
# eixo um é a linha horizontal (linha)
print("Soma do eixo zero",a.sum(axis=0))
print("Soma do eixo um",a.sum(axis=1))

Soma do eixo zero [4 6]
Soma do eixo um [3 7]


In [27]:
# informando o eixo para inserssão
# é passado o array 
# é passado o indice onde será inserido o novo elemento
# é passado o novo elemento 
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [29]:
# mas parece que ainda não houve mudança no array
a

array([[1, 2],
       [3, 4]])

In [31]:
np.insert(a,0,5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])

In [34]:
a

array([[1, 2],
       [3, 4]])

In [35]:
# criando novo array
novoArray = np.insert(a,0,5, axis=0)
print(novoArray)

[[5 5]
 [1 2]
 [3 4]]
