In [5]:
# NumPy é feito em c por isso é muito mais rapido que seus similares, 
# com ele pode-se construir um objeto array N-dimencional

import numpy as np

# criando um array
a = np.array([10,20,30,55])
print(a)
type(a)


[10 20 30 55]


numpy.ndarray

In [8]:
# criando uma matriz
matriz = np.array([[1,2],[3,4]])
print(matriz)

[[1 2]
 [3 4]]


In [10]:
# buscando um elemento especifico da matriz
matriz[1,1]

4

In [14]:
# ou tbm podei fazer assim
print(matriz[1][1])
print(matriz[-1][-1])
print(matriz[-1,-1])

4
4
4


In [20]:
# acessando todos os valores de uma linha
print(matriz[1,:])
print(matriz[0,:])

[3 4]
[1 2]


In [27]:
# acessando todos valores daquela coluna
print(matriz[ :,1])
print(matriz[ :,0])

[2 4]
[1 3]


In [29]:
# ver todos os metodos do meu objeto matriz
dir(matriz)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '_

In [32]:
# soma de matrizes
m1 = np.array([[1,2,3,4], [5,6,7,8]])
m2 = np.array([[9,1,11,12], [13,14,15,16]])
soma = m1 + m2 
print(soma)

[[10  3 14 16]
 [18 20 22 24]]


In [36]:
# subtração de matrizes 
soma - m2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
m1 * m2

array([[  9,   2,  33,  48],
       [ 65,  84, 105, 128]])

In [42]:
# soma elementos de uma matriz com numpy
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [43]:
#retorna o indice do maior valor
m3.argmax()

3

In [45]:
# ja para obter o indice do menor valor do array 
m3.argmin()

0

In [54]:
# NumPy versus Lista Python normal
import time
import numpy

inicio = time.time()

soma = 0
for i in range(1, 100000001):
    soma += i
fim = time.time()
print("\nTempo de um array normal = ",fim - inicio)

# Agora com Numpy
inicio2 = time.time()

numpy.arange(1, 100000001).sum()

fim2 = time.time()
print("\nTempo de um array usando NumPy = ",fim2 - inicio2)



Tempo de um array normal =  9.696132898330688

Tempo de um array usando NumPy =  0.27565479278564453


In [55]:
# slicing 
import numpy as np

l = [20, 30, 40, 55, 10]

# mostra os elementos começando no indice 1 e indo até o indice 3 não inclusivo, ou seja 
# para antes de mostrar o elemento do indice 3
print(l[1:3])

# omiti o inicio e o fim mas passei o parametro que diz de quantos a quantos
print(l[::2])


[30, 40]
[20, 40, 10]


In [58]:
# agora com numpy
a = np.array(l)
a

array([20, 30, 40, 55, 10])

In [60]:
print(a[1:3])
print(a[::2])

[30 40]
[20 40 10]


In [61]:
# 
#
a = np.array(l)
b = a[:]
b

array([20, 30, 40, 55, 10])

In [62]:
# na lista normal isso não aconteceria, mas nos Arrays do NumPy temos que tomar muito cuidado

b[0] = 1000
print(a)
print(b)

[1000   30   40   55   10]
[1000   30   40   55   10]


In [64]:
# a maneira correta de fazer copia de um array é assim :
c = a.copy()
print(a)
print(b)
print(c)

[1000   30   40   55   10]
[1000   30   40   55   10]
[1000   30   40   55   10]


In [66]:
a[0] = 33
c[0] = 5912
print(a)
print(b)
print(c)

[33 30 40 55 10]
[33 30 40 55 10]
[5912   30   40   55   10]
